### ISSUE TITLE
build failed on ubuntu 20.04

### ISSUE THREAD

**Issue by TheWaveLab** [facebook/watchman#1040]
I don't know what happened:

Traceback (most recent call last):
  File "build/fbcode_builder/getdeps.py", line 1275, in <module>

    sys.exit(main())
  File "build/fbcode_builder/getdeps.py", line 1258, in main
    return args.func(args)
  File "build/fbcode_builder/getdeps.py", line 109, in run
    self.run_project_cmd(args, loader, manifest)
  File "build/fbcode_builder/getdeps.py", line 627, in run_project_cmd
    builder.build(install_dirs, reconfigure=reconfigure)
  File "/mnt/f/codeforge/cpp/watchman-2022.07.04.00/build/fbcode_builder/getdeps/builder.py", line 137, in build
    self._build(install_dirs=install_dirs, reconfigure=reconfigure)
  File "/mnt/f/codeforge/cpp/watchman-2022.07.04.00/build/fbcode_builder/getdeps/builder.py", line 1085, in _build
    "-j%s" % self.num_jobs,
  File "/mnt/f/codeforge/cpp/watchman-2022.07.04.00/build/fbcode_builder/getdeps/builder.py", line 163, in num_jobs
    return self.build_opts.get_num_jobs(
  File "/mnt/f/codeforge/cpp/watchman-2022.07.04.00/build/fbcode_builder/getdeps/buildopts.py", line 184, in get_num_jobs
    available_ram = get_available_ram()
  File "/mnt/f/codeforge/cpp/watchman-2022.07.04.00/build/fbcode_builder/getdeps/platform.py", line 165, in get_available_ram
    return _get_available_ram_linux()
  File "/mnt/f/codeforge/cpp/watchman-2022.07.04.00/build/fbcode_builder/getdeps/platform.py", line 73, in _get_available_ram_linux
    raise NotImplementedError("/proc/meminfo had no valid MemAvailable")
NotImplementedError: /proc/meminfo had no valid MemAvailable

**Comment by chadaustin** [comment]
@TheWaveLab If you `cat /proc/meminfo`, what do you see? It's surprising the file would exist but have no MemAvailable field.

I can put up a patch to guess a reasonable value here.

**Comment by 36289108** [comment]
> I don't know what happened:
> 
> Traceback (most recent call last):
>   File "build/fbcode_builder/getdeps.py", line 1275, in <module>
> 
>     sys.exit(main())
>   File "build/fbcode_builder/getdeps.py", line 1258, in main
>     return args.func(args)
>   File "build/fbcode_builder/getdeps.py", line 109, in run
>     self.run_project_cmd(args, loader, manifest)
>   File "build/fbcode_builder/getdeps.py", line 627, in run_project_cmd
>     builder.build(install_dirs, reconfigure=reconfigure)
>   File "/mnt/f/codeforge/cpp/watchman-2022.07.04.00/build/fbcode_builder/getdeps/builder.py", line 137, in build
>     self._build(install_dirs=install_dirs, reconfigure=reconfigure)
>   File "/mnt/f/codeforge/cpp/watchman-2022.07.04.00/build/fbcode_builder/getdeps/builder.py", line 1085, in _build
>     "-j%s" % self.num_jobs,
>   File "/mnt/f/codeforge/cpp/watchman-2022.07.04.00/build/fbcode_builder/getdeps/builder.py", line 163, in num_jobs
>     return self.build_opts.get_num_jobs(
>   File "/mnt/f/codeforge/cpp/watchman-2022.07.04.00/build/fbcode_builder/getdeps/buildopts.py", line 184, in get_num_jobs
>     available_ram = get_available_ram()
>   File "/mnt/f/codeforge/cpp/watchman-2022.07.04.00/build/fbcode_builder/getdeps/platform.py", line 165, in get_available_ram
>     return _get_available_ram_linux()
>   File "/mnt/f/codeforge/cpp/watchman-2022.07.04.00/build/fbcode_builder/getdeps/platform.py", line 73, in _get_available_ram_linux
>     raise NotImplementedError("/proc/meminfo had no valid MemAvailable")
> NotImplementedError: /proc/meminfo had no valid MemAvailable
> 
> 

N

**Comment by chadaustin** [comment]
This is fixed now.
