### ISSUE TITLE
Version number problems when using with Semver

### ISSUE THREAD

**Issue by ktriponis** [facebook/watchman#107]
When I install watchman from sources and try to use ember-cli I get a problem with Semver complaining about version being invalid.

Here's a complete error message:

    Invalid Version: 3.2
    TypeError: Invalid Version: 3.2
        at new SemVer (/usr/local/lib/node_modules/ember-cli/node_modules/semver/semver.js:295:11)
        at Range.test (/usr/local/lib/node_modules/ember-cli/node_modules/semver/semver.js:1049:15)
        at Function.satisfies (/usr/local/lib/node_modules/ember-cli/node_modules/semver/semver.js:1098:16)
        at /usr/local/lib/node_modules/ember-cli/lib/models/watcher.js:107:29
        at lib$rsvp$$internal$$tryCatch (/usr/local/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
        at lib$rsvp$$internal$$invokeCallback (/usr/local/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
        at lib$rsvp$$internal$$publish (/usr/local/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
        at lib$rsvp$asap$$flush (/usr/local/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
        at process._tickCallback (node.js:355:11)

I guess the problem is that the version consists of only 2 segments, `3.2` instead of `3.2.0`.

**Comment by wez** [comment]
Ah, that's an unexpected side effect of our recent versioning adjustment.
https://reviews.facebook.net/D39183
will fix this, just want to run it by @sid0
