### ISSUE TITLE
Handling of `openssl` v3 in `getdeps.py` is broken

### ISSUE THREAD

**Issue by rakotomandimby** [facebook/watchman#1259]
When running `./autogen.sh` against `main` or `v2024.12.02.00`, I get:

```
Traceback (most recent call last):
File "/home/monconstat/Apps/watchman/build/fbcode_builder/getdeps.py", line 1478, in <module>
sys.exit(main())
^^^^^^
File "/home/monconstat/Apps/watchman/build/fbcode_builder/getdeps.py", line 1461, in main
return args.func(args)
^^^^^^^^^^^^^^^
File "/home/monconstat/Apps/watchman/build/fbcode_builder/getdeps.py", line 108, in run
self.run_project_cmd(args, loader, manifest)
File "/home/monconstat/Apps/watchman/build/fbcode_builder/getdeps.py", line 592, in run_project_cmd
fetcher = loader.create_fetcher(m)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/monconstat/Apps/watchman/build/fbcode_builder/getdeps/load.py", line 262, in create_fetcher
return manifest.create_fetcher(self.build_opts, self, ctx)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/monconstat/Apps/watchman/build/fbcode_builder/getdeps/manifest.py", line 476, in create_fetcher
fetcher = self._create_fetcher(build_options, ctx)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/monconstat/Apps/watchman/build/fbcode_builder/getdeps/manifest.py", line 470, in _create_fetcher
raise KeyError(
KeyError: 'project openssl has no fetcher configuration or system packages matching {distro=arch, distro_vers=None, fb=off, fbsource=off, os=linux, shared_libs=off, test=off}'
```

Note that `main` and `v2024.12.02.00` are using "openssl 3".

But if I build `v2024.11.25.00` (which is using "openssl 1.1.1l"), it works fine:

```
[monconstat@arch-00 watchman]$ ./autogen.sh 
+ PREFIX=/usr/local
+ python3 build/fbcode_builder/getdeps.py build --allow-system-packages --src-dir=. --project-install-prefix=watchman:/usr/local watchman
Building on {distro=arch, distro_vers=None, fb=off, fbsource=off, os=linux, shared_libs=off, test=on}
Testing ENV[BOOST_ROOT_1_69_0]: None
Testing ENV[BOOST_ROOT_1_69_0]: None
Assessing boost...
Assessing ninja...
Assessing cmake...
Assessing cpptoml...
Assessing fmt...
Assessing gflags...
Assessing glog...
Assessing googletest...
Assessing xxhash...
Assessing zstd...
Assessing double-conversion...
Assessing fast_float...
Assessing libdwarf...
Assessing libevent...
Assessing lz4...
Assessing snappy...
Assessing pcre2...
Assessing python-setuptools...
Assessing zlib...
Assessing bz2...
Assessing openssl...
Download with https://www.openssl.org/source/openssl-1.1.1l.tar.gz -> /tmp/fbcode_builder_getdeps-ZhomeZmonconstatZAppsZwatchmanZbuildZfbcode_builder/downloads/openssl-openssl-1.1.1l.tar.gz ...
 downloading 9834044 of 9834044  [Complete in 5.688452 seconds]
[...]

Extract /tmp/fbcode_builder_getdeps-ZhomeZmonconstatZAppsZwatchmanZbuildZfbcode_builder/downloads/openssl-openssl-1.1.1l.tar.gz -> /tmp/fbcode_builder_getdeps-ZhomeZmonconstatZAppsZwatchmanZbuildZfbcode_builder/extracted/openssl-openssl-1.1.1l.tar.gz
Installing /tmp/fbcode_builder_getdeps-ZhomeZmonconstatZAppsZwatchmanZbuildZfbcode_builder/extracted/openssl-openssl-1.1.1l.tar.gz -> /tmp/fbcode_builder_getdeps-ZhomeZmonconstatZAppsZwatchmanZbuildZfbcode_builder/installed/openssl-lz2c7df4jpF1755F3V93jPu3swCphj6FftKaZORQMh4
Assessing liboqs...
Download with https://github.com/open-quantum-safe/liboqs/archive/refs/tags/0.10.1.tar.gz -> /tmp/fbcode_builder_getdeps-ZhomeZmonconstatZAppsZwatchmanZbuildZfbcode_builder/downloads/liboqs-0.10.1.tar.gz ...
 downloading 4255203 of (Unknown)  [Complete in 11.016336 seconds]
Access-Control-Allow-Origin: https://render.githubusercontent.com
content-disposition: attachment; filename=liboqs-0.10.1.tar.gz
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
```

**Comment by Jr-14** [comment]
I get the same issue running `./autogen.sh` against `main`
