### ISSUE TITLE
watchman fails with argument --no-pretty

### ISSUE THREAD

**Issue by aakashlpin** [facebook/watchman#167]
This issue is related to react-native.

Started facing this issue today where trying to run `npm start` throws this error. It seems to be related to watchman.

Here's the error
```
Watchman:  watchman--no-pretty get-sockname returned with exit code 1 ERROR: Unknown option --no-pretty
```

Here's the stack trace
```
at ChildProcess.<anonymous> (/Users/aakashlpin/projects/cheapassApp/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/index.js:194:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

Any leads on what could be the potential issue?

**Comment by wez** [comment]
Can you check that you have installed watchman correctly?
What does `watchman version` output?

**Comment by wez** [comment]
It sounds like you have something else called `watchman` in your path

**Comment by aakashlpin** [comment]
@wez watchman version returns this -
![watchman](https://dl.dropbox.com/s/w2lgi38pb5wr6uf/Screenshot%202015-10-15%2021.03.07.png)

lemme see if `watchman` is what it should be.

**Comment by aakashlpin** [comment]
@wez yep. that was the issue. thanks a lot for the help!

**Comment by blin17** [comment]
What's the solution for this?

**Comment by wez** [comment]
If you have https://github.com/dfjones/watchman installed, remove it.
