### ISSUE TITLE
Pywatchman error on FreeBSD

### ISSUE THREAD

**Issue by tony** [facebook/watchman#176]
```
$ freebsd-version -ku; uname -apKU 
11.0-CURRENT
11.0-CURRENT
FreeBSD x230 11.0-CURRENT FreeBSD 11.0-CURRENT #0: Wed Oct  7 17:47:58 CDT 2015     root@x230:/usr/obj/usr/src/sys/MYKERNEL  amd64 amd64 1100080 1100080

$ pkg info watchman
watchman-3.0.0
Name           : watchman
Version        : 3.0.0
Installed on   : Thu Oct 22 09:46:52 CDT 2015
Origin         : sysutils/watchman
Architecture   : freebsd:11:x86:64
Prefix         : /usr/local
Categories     : sysutils
Licenses       : APACHE20
Maintainer     : linpct@gmail.com
WWW            : https://facebook.github.io/watchman/
Comment        : File alteration monitoring service
Shared Libs required:
        libpcre.so.1
Annotations    :
        repo_type      : binary
        repository     : FreeBSD
Flat size      : 163KiB
Description    :
Watchman exists to watch files and record when they change.  It can also
trigger actions (such as rebuilding assets) when matching files change.

WWW: https://facebook.github.io/watchman/


$ watchman-make -p '**/*.py' --make './run-tests.py' -t test
Traceback (most recent call last):
  File "/usr/home/tony/study/python/tmuxp/.env/bin/watchman-make", line 171, in <module>
    required=['cmd-watch-project', 'wildmatch'])
  File "/usr/home/tony/study/python/tmuxp/.env/lib/python2.7/site-packages/pywatchman/__init__.py", line 509, in capabilityCheck
    capabilities.synthesize(res, opts)
NameError: global name 'opts' is not defined
```

If this is related to packaging / an update needed on the FreeBSD package end of things, I'll file a ticket on that end.

**Comment by wez** [comment]
Yeah, 3.0 is relatively old.  The python errors may go away if you reinstall pywatchman from pip, but it will require a newer version of watchman to successfully run watchman-make and watchman-wait.

If you can file a ticket with the ports bits to update to the v4.1.0 tag and release, that would be great

**Comment by tony** [comment]
Built 4.1.0 from source and it's working great so far on 11-CURRENT.

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=203961

**Comment by wez** [comment]
I'm going to close this issue since you're up and running and 4.1.0 is pending in ports.
Thanks for reporting this!

**Comment by tony** [comment]
@wez :+1:
