### ISSUE TITLE
Bad format string in pybser.loads

### ISSUE THREAD

**Issue by DRMacIver** [facebook/watchman#181]
```python
from pywatchman.pybser import loads
loads("\x00\x01\n")
```

Results in the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pywatchman/pybser.py", line 290, in loads
    expected_len, pos = _bunser_int(buf, 2)
  File "pywatchman/pybser.py", line 205, in _bunser_int
    raise RuntimeError('Invalid bser int encoding 0x%02x' % (int_type,))
TypeError: %x format: a number is required, not str
```

**Comment by wez** [comment]
Thanks, fixed in master!
