### ISSUE TITLE
IndexError when parsing bad bcer data

### ISSUE THREAD

**Issue by DRMacIver** [facebook/watchman#182]
```python
from pywatchman.pybcer import loads
loads('\x00\x01\x04\x01\x00\x02')
```

This raises the following exception:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pywatchman/pybser.py", line 293, in loads
    return _bser_loads_recursive(buf, pos)[0]
  File "pywatchman/pybser.py", line 269, in _bser_loads_recursive
    return _bunser_string(buf, pos)
  File "pywatchman/pybser.py", line 211, in _bunser_string
    str_len, pos = _bunser_int(buf, pos + 1)
  File "pywatchman/pybser.py", line 191, in _bunser_int
    int_type = buf[pos]
IndexError: string index out of range
```

Which is probably unintended behaviour.

**Comment by wez** [comment]
Thanks, fixed in master!
