### ISSUE TITLE
ImportError: DLL load failed: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by JamesDiGriz** [facebook/watchman#206]
hgwatchman + watchman.exe (amd64) does not work with TortoiseHg 3.6.2 (amd64). Also does not work with pure Mercurial 3.6.3 (amd64).

    #!python
    ** Mercurial version (3.6.2).  TortoiseHg version (3.6.2)
    ** Command: --nofork commit
    ** CWD: C:\T1\hg\comm-central
    ** Encoding: cp1252
    ** Extensions loaded: extdiff, fetch, hgk, relink, graphlog, patience, hggit, hgsubversion, hgwatchman, transplant, convert, rebase, record, bugzilla, strip, mq, shelve, evolve, histedit
    ** Python version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
    ** Windows version: sys.getwindowsversion(major=6, minor=1, build=7601, platform=2, service_pack='Service Pack 1')
    ** Processor architecture: x64
    ** Qt-4.8.6 PyQt-4.11.3 QScintilla-2.8.4
    Traceback (most recent call last):
      File "tortoisehg\hgqt\status.pyo", line 663, in run
      File "c:/T1/hg/hgwatchman\hgwatchman\__init__.py", line 468, in status
      File "c:/T1/hg/hgwatchman\hgwatchman\__init__.py", line 334, in overridestatus
      File "c:/T1/hg/hgwatchman\hgwatchman\client.py", line 54, in getcurrentclock
      File "c:/T1/hg/hgwatchman\hgwatchman\client.py", line 92, in command
      File "c:/T1/hg/hgwatchman\hgwatchman\client.py", line 81, in _command
      File "c:/T1/hg/hgwatchman\hgwatchman\pywatchman\__init__.py", line 507, in query
      File "c:/T1/hg/hgwatchman\hgwatchman\pywatchman\__init__.py", line 417, in _connect
      File "c:/T1/hg/hgwatchman\hgwatchman\pywatchman\__init__.py", line 404, in _resolvesockname
      File "mercurial\demandimport.pyo", line 130, in __getattribute__
      File "mercurial\demandimport.pyo", line 96, in _load
      File "mercurial\demandimport.pyo", line 53, in _hgextimport
    ImportError: DLL load failed: %1 is not a valid Win32 application.
    
watchman log file:

2016-01-04T06:06:11,988: [listener] Watchman 4.3.0 <no build info set> starting up on lenovo-PC
2016-01-04T06:06:11,988: [listener] Using watcher mechanism win32
2016-01-04T06:06:11,988: [listener] failed to parse json from C:\Users\Philip\AppData\Local\Temp\Philip-state\state: unable to open C:\Users\Philip\AppData\Local\Temp\Philip-state\state: No such file or directory
2016-01-04T06:06:11,988: [listener] waiting for pipe clients on \\.\pipe\watchman-Philip
2016-02-01T01:06:56,031: [listener] Watchman 4.4.0 <no build info set> starting up on lenovo-PC
2016-02-01T01:06:56,046: [listener] Using watcher mechanism win32
2016-02-01T01:06:56,046: [listener] failed to parse json from C:\Users\Philip\AppData\Local\Temp\Philip-state\state: unable to open C:\Users\Philip\AppData\Local\Temp\Philip-state\state: No such file or directory
2016-02-01T01:06:56,046: [listener] waiting for pipe clients on \\.\pipe\watchman-Philip
2016-02-01T22:34:20,608: [listener] Watchman 4.1.0 <no build info set> starting up on lenovo-PC
2016-02-01T22:34:20,623: [listener] Using watcher mechanism win32
2016-02-01T22:34:20,623: [listener] failed to parse json from C:/Users/Philip/AppData/Local/Temp\Philip-state\state: unable to open C:/Users/Philip/AppData/Local/Temp\Philip-state\state: No such file or directory
2016-02-01T22:34:20,623: [listener] waiting for pipe clients on \\.\pipe\watchman-Philip

**Comment by wez** [comment]
Sounds like the bser python module didn't get built correctly.
Do you have a bser.dll somewhere under your c:/T1/hg/hgwatchman dir?
Did you build hgwatchman or just clone it and use it?
We do a pure python bser implementation that should have been picked up as a fallback, but it seems like the demandimport stuff may have prevented that from working correctly :-/

**Comment by JamesDiGriz** [comment]
> Sounds like the bser python module didn't get built correctly.
> Do you have a bser.dll somewhere under your c:/T1/hg/hgwatchman dir?
Not found.

> Did you build hgwatchman or just clone it and use it?
I followed the instructions in the README.md file

    :::sh
    hg clone https://bitbucket.org/facebook/hgwatchman
    cd hgwatchman
    make local 

Also I tried the watchman.exe that comes with mozilla-build. I also tried cloning and building watchman with Visual Studio.

> We do a pure python bser implementation that should have been picked up as a 
> fallback, but it seems like the demandimport stuff may have prevented that 
> from working correctly :-/

I found: bser.exp bser.lib bser.pyd.manifest and bser.obj in:
c:\T1\hg\hgwatchman\build\temp.win32-2.7\Release\hgwatchman\pywatchman\bser.obj

**Comment by JamesDiGriz** [comment]
With mercurial 3.9 (with built in fsmonitor) and latest watchman x64 built from source this problem does not exist. Whether watchman is actually working is another question
