### ISSUE TITLE
Nuclide can't use watchman

### ISSUE THREAD

**Issue by russoue** [facebook/watchman#443]
I am using watchman to use `nuclide` and am repeatedly getting the following error message. I have used the `4.7.0` release of watchman, the nuclide plugin and server version is `0.211.0` and my OS is `Linux raspberrypi-2 4.4.50-v7+`. Please help.

```
Watchman Error:Remote Error: The client was ended processing message {"protocol":"service_framework3_rpc","type":"call","method":"FileWatcherService/watchDirectoryRecursive","id":11,"args":{"directoryPath":"/home/russoue/code"}} "Error: The client was ended\n at Client.cancelCommands (/usr/local/lib/node_modules/nuclide/node_modules/fb-watchman/index.js:52:15)\n at Client.end (/usr/local/lib/node_modules/nuclide/node_modules/fb-watchman/index.js:315:8)\n at Client. (/usr/local/lib/node_modules/nuclide/pkg/nuclide-watchman-helpers/lib/WatchmanClient.js:101:16)\n at emitOne (events.js:96:13)\n at Client.emit (events.js:191:7)\n at spawnError (/usr/local/lib/node_modules/nuclide/node_modules/fb-watchman/index.js:170:10)\n at ChildProcess. (/usr/local/lib/node_modules/nuclide/node_modules/fb-watchman/index.js:193:5)\n at emitOne (events.js:96:13)\n at ChildProcess.emit (events.js:191:7)\n at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)"
```

**Comment by wez** [comment]
Can you provide your watchman logs?  There's a section in https://facebook.github.io/watchman/docs/troubleshooting.html that should help you locate them.

Can you try some basic commands for yourself, outside of nuclide, and share the output?

```
watchman watch-project /home/russoue/code
```

**Comment by russoue** [comment]
@wez, thanks for the quick reply. I tried the basic command and it all looks fine to me:

```
russoue@raspberrypi-2:~/code $ watchman watch-project /home/russoue/code
{
    "version": "4.7.0",
    "watch": "/home/russoue/code",
    "watcher": "inotify"
}
russoue@raspberrypi-2:~/code $ pgrep watchman
1827
russoue@raspberrypi-2:~/code $ ls /usr/local/var/run/watchman/russoue-state/
log  pid  sock  state
russoue@raspberrypi-2:~/code $ cat /usr/local/var/run/watchman/russoue-state/pid
1827
russoue@raspberrypi-2:~ $ watchman shutdown-server
{
    "version": "4.7.0",
    "shutdown-server": true
}
```

But I am seeing the same error while using Nuclide and the content of the `/usr/local/var/run/watchman` doesn't change i.e. nothing new gets added/updated.

**Comment by wez** [comment]
I'd love to see your watchman logs; the `/usr/local/var/run/watchman/russoue-state/log` file is the one I'd like to see.  Can you share them with me?

Have you reached out to the folks in the Nuclide project to see if there are more diagnostics from the Nuclide side?

**Comment by russoue** [comment]
@wez, here is the content of the log:

```
russoue@raspberrypi-2:~ $ cat !$
cat /usr/local/var/run/watchman/russoue-state/log
2017-03-29T18:37:55,600: [listener] Watchman 4.7.0 <no build info set> starting up on raspberrypi-2
2017-03-29T18:37:55,601: [listener] failed to parse json from /usr/local/var/run/watchman/russoue-state/state: unable to open /usr/local/var/run/watchman/russoue-state/state: No such file or directory
2017-03-29T18:37:55,611: [client=0xa5d350:stm=0xa5cf50] path /home/russoue/code is on filesystem type unknown
2017-03-29T18:37:55,612: [client=0xa5d350:stm=0xa5cf50] root /home/russoue/code using watcher mechanism inotify (auto was requested)
2017-03-29T18:37:55,708: [io /home/russoue/code] PERF: {"meta": {"root": {"path": "/home/russoue/code", "number": 1, "recrawl_count": 0, "ticks": 2, "case_sensitive": true, "watcher": "inotify"}}, "ru_nsignals": 0, "pid": 20445, "ru_idrss": 0, "description": "full-crawl", "ru_msgrcv": 0, "ru_inblock": 0, "ru_nswap": 0, "ru_majflt": 0, "start_time": 1490837875.613292, "version": "4.7.0", "ru_nivcsw": 0, "elapsed_time": 0.095003000000000004, "ru_maxrss": 260, "user_time": 0.02, "ru_ixrss": 0, "system_time": 0.080000000000000002, "ru_minflt": 82, "ru_oublock": 0, "ru_msgsnd": 0, "ru_nvcsw": 2}
2017-03-29T18:37:55,708: [io /home/russoue/code] crawl complete
```

Please note that this log appears after running `watchman watch-project /home/russoue/code` and does not get updated if I run Nuclide. I will check with the Nuclide guys too. Thank you.

**Comment by russoue** [comment]
I opened https://github.com/facebook/nuclide/issues/1075.

**Comment by russoue** [comment]
@wez, It's now working perfectly after I updated Nuclide to version `0.213.0`. Thanks a lot for helping.
