### ISSUE TITLE
Watchman errors with exit code=3221225781

### ISSUE THREAD

**Issue by BrennanR** [facebook/watchman#464]
I'm trying to use `relay-compiler` on windows, which seems to depend on watchman. I've followed the steps outlined here: https://github.com/facebook/watchman/issues/19 for windows support, yet I'm still running into this error. Windows, node, and npm version can be seen below.

```
> relay-compiler --src ./assets --schema schema.json

HINT: pass --watch to keep watching for changes.
Watchman:  watchman --no-pretty get-sockname returned with exit code=3221225781, signal=null, stderr= 
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: watchman --no-pretty get-sockname returned with exit code=3221225781, signal=null, stderr= 
    at ChildProcess.<anonymous> (C:\Users\Brennan\PycharmProjects\StockTracker\node_modules\fb-watchman\index.js:198:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:511:12)

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "relay" "--scripts-prepend-node-path"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stock-tracker@1.0.0 relay: `relay-compiler --src ./assets --schema schema.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the stock-tracker@1.0.0 relay script 'relay-compiler --src ./assets --schema schema.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
```

Any ideas as to what the issue might be?

**Comment by wez** [comment]
What happens if you run `watchman --no-pretty get-sockname` from a command prompt?

**Comment by wez** [comment]
Anything useful in the watchman logs?  https://facebook.github.io/watchman/docs/troubleshooting.html#where-are-the-logs

**Comment by wez** [comment]
My best guess is that you installed the npm watchman package globally.  That's not the same thing as the facebook watchman service, despite the unfortunate naming clash.
