### ISSUE TITLE
[node fb-watchman] cannot handle error when watchman is not installed

### ISSUE THREAD

**Issue by robrichard** [facebook/watchman#509]
[From the docs:](https://facebook.github.io/watchman/docs/nodejs.html#checking-for-watchman-availability)

```js
var watchman = require('fb-watchman');
var client = new watchman.Client();
client.capabilityCheck({optional:[], required:['relative_root']},
  function (error, resp) {
    if (error) {
      // error will be an Error object if the watchman service is not
      // installed, or if any of the names listed in the `required`
      // array are not supported by the server
      console.error(error);
    }
    // resp will be an extended version response:
    // {'version': '3.8.0', 'capabilities': {'relative_root': true}}
    console.log(resp);
  });
```

If watchman is not installed, what actually happens is an `Unhandled 'error' event` is thrown and cannot be caught. The only way to catch this is to add a `client.on('error', ...)` callback. This is doable but then further precaution needs to be taken to avoid catching other errors in that callback. It would be much more convenient if it worked as documented. I have a minimal reproduction example here: https://github.com/robrichard/watchman-error/blob/master/index.js

**Comment by wez** [comment]
I don't quite follow what the failure mode is; can you provide a stack trace of the problematic situation to show what's going wrong?

**Comment by robrichard** [comment]
If you run the example above ([taken directly from the watchman docs](https://facebook.github.io/watchman/docs/nodejs.html#checking-for-watchman-availability)), you will get this error:

```js
Watchman:  Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

Instead I would expect the callback to be called with an error argument, and `watchman not installed` to be logged so the application can handle the error gracefully. It's also not possible to catch this error by wrapping the function with a `try/catch` block.

This other example shows the only way to handle the error is by attaching an `error` event listener: https://github.com/robrichard/watchman-error/blob/master/index.js

**Comment by fllprbt** [comment]
Same behavior happened to my case, any updates on it?
