### ISSUE TITLE
autogen.sh Error

### ISSUE THREAD

**Issue by maedewiza** [facebook/watchman#734]
I tried to upgrade git and reinstall python. On macOS.

```
==> ./autogen.sh
+ case "$OSTYPE" in
+ command -v brew
+ test '!' -d external
+ ./getdeps.py --install-deps
Installing necessary packages via Homebrew...
+ brew install autoconf automake bison boost boost-python cmake curl double-conversion flex gflags glog libevent libgit2 libtool lz4 openssl snappy xz zstd
Traceback (most recent call last):
  File "./getdeps.py", line 608, in <module>
    main()
  File "./getdeps.py", line 587, in main
    install_platform_deps()
  File "./getdeps.py", line 516, in install_platform_deps
    allow_fail=True,
  File "./getdeps.py", line 275, in run_cmd
    subprocess.call(cmd, env=env, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory


```

**Comment by mithun-mohan** [comment]
@maedewiza Even i was facing the same issue when i cloned the Repo. It seems the current master has some bug that is causing this issue. Try the following, which actually worked for me;
#### Checkout to the latest stable release, which when i used was 'v4.9.0';
`git checkout tags/v4.9.0`

#### Now try executing 'autogen.sh' script;
`./autogen.sh`

**Comment by wez** [comment]
We've changed the build process a lot since 4.9.0 and since this issue was opened.  I'm going to close it out because it's been so long and changed so much.
