### ISSUE TITLE
Error by FSEventStreamStart 

### ISSUE THREAD

**Issue by pcjpcj2** [facebook/watchman#82]
FSEventStreamStart failed
Error: FSEventStreamStart failed
at null. (/Users/ChangJooPark/Development/ember-blog/node_modules/ember-    cli/node_modules/broccoli-sane-watcher/node_modules/sane/node_modules/fb-    watchman/index.js:84:23)
at emit (events.js:95:17)
at null. (stream_readable.js:765:14)
at emit (events.js:92:17)
at emitReadable (_stream_readable.js:427:10)
at emitReadable (_stream_readable.js:423:5)
at readableAddChunk (_stream_readable.js:166:9)
at Readable.push (_stream_readable.js:128:10)
at Transform.push (_stream_transform.js:140:32)
at JSONStream._transform (/Users/ChangJooPark/Development/ember-blog/node_modules/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/node_modules/fb-watchman/node_modules/json-stream/lib/json-stream.js:30:14)

I use Ember-cli and related watchman for live-reload.

why this message occured?

my system contains OSX yosemite, npm - 2.1.8 , ember 0.1.15, node 0.10.35 and watchman 3.0.0

**Comment by wez** [comment]
Take a look at https://github.com/ember-cli/ember-cli/issues/2683
Are you using Sublime?  Users there report that closing and re-opening Sublime solves their problems.

**Comment by pcjpcj2** [comment]
Thanks @wez  :+1:
