### ISSUE TITLE
watchman error please help me on ubuntu

### ISSUE THREAD

**Issue by Arupkarbabu** [facebook/watchman#827]
jest-haste-map: Watchman crawl failed. Retrying once with node crawler.
  Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file in your project's root folder or initialize a git or hg repository in your project.
  Error: Watchman error: A non-recoverable condition has triggered.  Watchman needs your help!
The triggering condition was at timestamp=1592389338: inotify-add-watch(/home/arup/Documents/react_native/1/node_modules/deepmerge) -> The user limit on the total number of inotify watches was reached; increase the fs.inotify.max_user_watches sysctl
All requests will continue to fail with this message until you resolve
the underlying problem.  You will find more information on fixing this at
https://facebook.github.io/watchman/docs/troubleshooting.html#poison-inotify-add-watch. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.html.

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: A non-recoverable condition has triggered.  Watchman needs your help!
The triggering condition was at timestamp=1592389338: inotify-add-watch(/home/arup/Documents/react_native/1/node_modules/deepmerge) -> The user limit on the total number of inotify watches was reached; increase the fs.inotify.max_user_watches sysctl
All requests will continue to fail with this message until you resolve
the underlying problem.  You will find more information on fixing this at
https://facebook.github.io/watchman/docs/troubleshooting.html#poison-inotify-add-watch

    at ChildProcess.<anonymous> (/home/arup/Documents/react_native/1/node_modules/fb-watchman/index.js:207:21)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1026:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
Emitted 'error' event on WatchmanWatcher instance at:
    at Client.<anonymous> (/home/arup/Documents/react_native/1/node_modules/jest-haste-map/build/lib/WatchmanWatcher.js:130:10)
    at Client.emit (events.js:315:20)
    at ChildProcess.<anonymous> (/home/arup/Documents/react_native/1/node_modules/fb-watchman/index.js:214:12)
    at ChildProcess.emit (events.js:315:20)
    [... lines matching original stack trace ...]
    at Pipe.<anonymous> (net.js:674:12) {
  watchmanResponse: {
    version: '4.9.0',
    error: 'A non-recoverable condition has triggered.  Watchman needs your help!\n' +
      'The triggering condition was at timestamp=1592389338: inotify-add-watch(/home/arup/Documents/react_native/1/node_modules/deepmerge) -> The user limit on the total number of inotify watches was reached; increase the fs.inotify.max_user_watches sysctl\n' +
      'All requests will continue to fail with this message until you resolve\n' +
      'the underlying problem.  You will find more information on fixing this at\n' +
      'https://facebook.github.io/watchman/docs/troubleshooting.html#poison-inotify-add-watch\n'
  }
}

**Comment by wez** [comment]
Sorry, the links are broken at the moment due to some recent website changes.
This link has more information:

https://facebook.github.io/watchman/docs/troubleshooting/#poison-inotify-add-watch

**Comment by omar-belaqziz-nw** [comment]
I had the same problem with Ubuntu 22.04 LTS.
To understand the problem you should know that:
- Metro is a JavaScript bundler used primarily for building React Native applications. It uses Watchman to watch for changes to the project files, so that it can automatically rebuild the project when changes are detected.
- Watchman uses the “inotify watches” feature provided by the Linux kernel to monitor file changes.
- The user limit on the total number of inotify watches was reached.

To solve this you, need to raise the limit by running the following commands:
`echo 999999 | sudo tee -a /proc/sys/fs/inotify/max_user_watches`
and
`watchman shutdown-server`

Here are some useful links:
https://github.com/facebook/watchman
https://facebook.github.io/watchman/docs/troubleshooting.html#poison-inotify_add_watch
https://facebook.github.io/watchman/docs/install.html#system-specific-preparation

**Comment by aadil42** [comment]
Thanks, man for explaining @omar-belaqziz-nw. It worked.
