### ISSUE TITLE
Cannot compile on Linux Mint 20.3 "Una"(Ubuntu 20.04)

### ISSUE THREAD

**Issue by franklin-vidal** [facebook/watchman#990]
Hello,

After trying to compile i get the error:

```
+ PREFIX=/usr/local
+ python3 build/fbcode_builder/getdeps.py build --src-dir=. watchman --project-install-prefix=watchman:/usr/local
Building on {distro=mint, distro_vers=20.3, fb=off, os=linux, test=on}
Assessing boost...
Assessing ninja...
Assessing openssl...
Traceback (most recent call last):
  File "build/fbcode_builder/getdeps.py", line 1130, in <module>
    sys.exit(main())
  File "build/fbcode_builder/getdeps.py", line 1113, in main
    return args.func(args)
  File "build/fbcode_builder/getdeps.py", line 108, in run
    self.run_project_cmd(args, loader, manifest)
  File "build/fbcode_builder/getdeps.py", line 563, in run_project_cmd
    builder = m.create_builder(
  File "/home/frk/Downloads/watchman-2022.01.10.00/build/fbcode_builder/getdeps/manifest.py", line 448, in create_builder
    raise Exception("project %s has no builder for %r" % (self.name, ctx))
Exception: project openssl has no builder for <getdeps.manifest.ManifestContext object at 0x7efefb7110d0>
```

**Comment by chadaustin** [comment]
Fixed by https://github.com/facebook/watchman/commit/7c31dfdb1c8c44d261447e9b03b79492c025a9e3
